name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy:
    name: Terraform destroy all resources
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI login
        run: |
          az login \
            --username "${{ secrets.AZURE_USERNAME }}" \
            --password "${{ secrets.AZURE_PASSWORD }}"
          az account set \
            --subscription "3088b175-92ef-4dd7-9020-ee7ae696fd1a"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.x"

      - name: Terraform init
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform init
        working-directory: terraform/

      - name: Terraform destroy
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_admin_ip: ${{ secrets.ADMIN_IP }}
        run: terraform destroy -auto-approve -lock=false
        working-directory: terraform/

      - name: Verify resource group gone
        run: |
          az group list \
            --query "[?starts_with(name,'rg-alchemyst')].{Name:name,State:properties.provisioningState}" \
            -o table
